### ISSUE TITLE
Example notebook code fails to run due to missing runtime config file

### ISSUE THREAD

**Issue by mungojam** [filmor/clr-loader#2]
I'm having a go at getting this up and running so I can look into compatibility with .net core self-contained mode (I have a feeling it will 'just work' with a small tweak).

But when I try to run the example code from the example notebook, it seems to be missing `example.runtimeconfig.json` file:

> T h e   s p e c i f i e d   r u n t i m e c o n f i g . j s o n   [ e x a m p l e / o u t / e x a m p l e . r u n t i m e c o n f i g . j s o n ]   d o e s   n o t   e x i s t

The code I try to run is:

```python
from clr_loader import hostfxr
from clr_loader.ffi import ffi

core = hostfxr.HostFxr("example/out/example.runtimeconfig.json")
```

**Comment by filmor** [comment]
You need to compile the example against netcoreapp30 like this: `cd example; dotnet build -o out -f netcoreapp30`

**Comment by bneumann** [comment]
Yeah good tip. It gave me "InvalidConfigFile" because it builds netstandard if no framework is given.

**Comment by mungojam** [comment]
Thanks both, happy to close
